# Generated by Django 3.0.3 on 2020-09-05 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'description'], name='api_movie_title_f9235a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title',)},
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['movie', 'user'], name='api_rating_movie_i_417860_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('movie', 'user')},
        ),
    ]
