# Generated by Django 3.0.3 on 2020-09-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rating',
            name='api_rating_movie_i_417860_idx',
        ),
        migrations.AddField(
            model_name='rating',
            name='stars',
            field=models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['movie'], name='api_rating_movie_i_a96108_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['user'], name='api_rating_user_id_1b0478_idx'),
        ),
    ]
